# basically copied straight from here: https://github.com/Arzte/Arzte-bot/blob/master/.github/workflows/create_release.yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

name: Create/Upload Release

jobs:
  build:
    name: Create/Upload Release
    runs-on: ubuntu-latest
    #services:
      #postgres:
        #image: postgres:alpine
        #env:
        #  POSTGRES_USER: postgres
        #  POSTGRES_PASSWORD: postgres
        #  POSTGRES_DB: postgres
        #ports:
          # will assign a random free host port
        #  - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        #options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Build/Upload Docker container
        id: build-docker-container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: notkanbaru
          password: "${{ secrets.GITHUB_TOKEN }}"  # you don't need to manually set this secret. GitHub does it on your behalf
          registry: docker.pkg.github.com
          image_name: gif